# Generated by Django 5.2.7 on 2025-11-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('electricity', 'Electricity'), ('road', 'Road'), ('sanitation', 'Sanitation'), ('water_supply', 'Water Supply'), ('others', 'Others')], default='others', max_length=20),
            preserve_default=False,
        ),
    ]
