# Generated by Django 5.2.4 on 2025-11-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_complaint_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='complaint_photos/'),
        ),
    ]
