# Generated by Django 5.2.4 on 2025-11-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_complaint_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='assigned_department',
            field=models.CharField(blank=True, choices=[('admin', 'Central Administration'), ('power', 'Power & Electricity'), ('health', 'Public Health & Engineering'), ('works', 'Public Works')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='complaint',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('admin', 'Central Administration'), ('power', 'Power & Electricity'), ('health', 'Public Health & Engineering'), ('works', 'Public Works')], max_length=20, null=True),
        ),
    ]
